version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  producer:
    build: ./producer
    env_file: ./producer/.env
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq

  consumer:
    build: ./consumer
    env_file: ./consumer/.env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started

volumes:
  pgdata:
